### PR TITLE
ienumerable support

### PR DESCRIPTION
**Pull request by salehjafarli**

### CODE REVIEW

**Comment by ronaldbosma** [comment]
Thanks for the PR. I'll have a look at it soon.

If you can provide a couple of unit tests in the meantime, that would be great.

**Comment by salehjafarli** [comment]
Thanks for responding, sure i will be providing unit tests for PR soon

**Comment by salehjafarli** [comment]
> Thanks for the PR. I'll have a look at it soon.
> 
> If you can provide a couple of unit tests in the meantime, that would be great.

Thanks for responding, sure i will be providing unit tests for PR soon

**Comment by salehjafarli** [comment]
> Thanks for the PR. I'll have a look at it soon.
> 
> If you can provide a couple of unit tests in the meantime, that would be great.

Hi, I provided test, please check

**Comment by ronaldbosma** [comment]
@salehjafarli Thank you for your patience. I've further improved the test and added an additional scenario that checks whether the mock verify fails when `IntProperty` is not ignored.

_You can ignore the pipeline failure. It occurs when pushing a prerelease NuGet package to Azure DevOps artifacts due to insufficient permissions because it's triggered from a GitHub PR._

**Pull request merged**
